### PR TITLE
Tickets/sitcom 1224

### PR DESCRIPTION
**Pull request by ltoribiosc**

### CODE REVIEW

**Comment by bstalder** [comment]
please clear outputs from the notebooks, and remove the M1M3 notebook (not associated with this ticket).

**Comment by ltoribiosc** [comment]
<p>I have just deleted the M1M3 files.</p>

**Comment by bstalder** [comment]
please clear outputs.  check units in plots (should be angles).  I didn't see where we calculate the Joules being discharged from the capacitor bank, only Coulombs which isn't exactly what we want/need.

**Comment by ltoribiosc** [comment]
<p>I am reviewing the code and (if I am not mistaken) the Joules that are discharged from the capacitor bank are calculated, but I got confused when making the graphs and I put Coulombs on the axis.</p><p> </p><p>The work (in Joules) is calculated as the integral during the movement (slew) of the current multiplied by the voltage. What I call total energy.</p><p> </p><p>energy_total = np.trapz(power_df.powerSupplyCurrent * power_df.powerSupplyVoltage)</p><p> </p><p>I'm going to review it one more time and change the axes of the graphs. I'll let you know when it's ready so you can tell me if it's correct.</p><p> </p><p> Thank you</p>

**Comment by ltoribiosc** [comment]
<p>Brian, I still have to clean up the outputs but could you please check that it now shows what is needed?</p>

**Review by bstalder — CHANGES_REQUESTED** [review]
large volume of plots generated as png files, especially the slew profiles.  perhaps make an example set of plots for a single night (and single slew profile), and plot them in-line (and just explain how to generate for other nights).

**Comment by ltoribiosc** [comment]
I have commented in all functions the option to save the .png. Especially, in the analysis of the slews, I have added an option to save the figures as .png or not. I have left the option of being able to save them, because it can be interesting to study all of them in one night. I've also had some examples shown online.

I have also added comments to know how to remove only the examples from being shown, save the .png or not and change the observation night

**Comment by bstalder** [comment]
checked notebook functions.  still need to clear outputs, but looks good.

**Comment by ltoribiosc** [comment]
Brian, excuse me because maybe I'm not understanding what you are asking me to do. I have cleaned up the output and uploaded the new clean version. If you run the notebook, the plots appear again, don't you want them to appear?

**Comment by bstalder** [comment]
<p>you need to clear your cell outputs in this notebook before you commit them.  this is in order to more cleanly track any changes.</p>

**Comment by ltoribiosc** [comment]
Now all the output cells should appear clean. Do you still see information in the outputs? Last time, I made the commit clearing all the cells

**Review by bstalder — APPROVED** [review]
removed cell outputs looks good.

**Comment by bstalder** [comment]
pull request approved.

**Pull request merged**
