### PR TITLE
Tickets/sitcom 1485

### PR DESCRIPTION
**Pull request by Kelks19**
There may be some minor typos and clarifications needed — the notebook as it reads now is with my own personal notes. 
There is also this thing with notebook that I cannot get it to show hosrizontal scrollbar to slew the output cell with plot. It has driven me nuts :/ . Let me know if you have a solution for that !

### CODE REVIEW

**Comment by ltoribiosc** [comment]
<p>This notebook explores the possible sources and/or components affected by the vibrations observed on 9 and 10 March 2024 at the Top End Assembly (TEA).</p><p> </p><p>In particular, this analysis focuses on <strong>the hexapods of the MTCam</strong> and the vibrations it may or may not have experienced during the event.</p><p> </p><p>At the beginning of the notebook there is a summary of an earlier analysis (SITCOM-1285), which is very useful.</p><p> </p><p>It analyses the actual positions consisting of 6 axes of motion (x,y,z,u,v,w) and the current. In addition, amplitude and rms are used to determine the changes in the data as a function of time and FFT analysis is used to determine the frequency.&nbsp;</p>

**Comment by ltoribiosc** [comment]
<p>To make the analysis clearer, it would be useful to add some comments in the section ‘Vibration time windows’ indicating that the different options should be commented and uncommented depending on the day to be analysed.&nbsp;</p>

**Comment by ltoribiosc** [comment]
<p>In the cell where the options are, if any of them is not necessary, you should delete it.</p>

**Comment by ltoribiosc** [comment]
<p>I don't know if it would be interesting to point out in the graphs that the natural frequency of both Camera and M2 hexapods is around 12 Hz. To be able to see the difference with the vibration frequency that is being found now. Right now the 12Hz frequency is not visible in the graphs, why is this happening?</p>

**Comment by ltoribiosc** [comment]
<p>In fig3, in ax00.set_ylabel, remove a u from ‘Cuurent (A)’.</p>

**Comment by ltoribiosc** [comment]
<p>In fig4, last plots, change this part:</p><p> </p><p>fig1.suptitle(f"CamHex Vibrations: {name} on {event}", fontsize=20)</p><p>fig1.tight_layout(pad=2)&nbsp;</p><p> </p><p>It should put fig4, not fig1. That's why the title does not appear in the figures</p>

**Comment by Kelks19** [comment]
> I don't know if it would be interesting to point out in the graphs that the natural frequency of both Camera and M2 hexapods is around 12 Hz. To be able to see the difference with the vibration frequency that is being found now. Right now the 12Hz frequency is not visible in the graphs, why is this happening?

So, what we are Fourier-transforming is the residual of e.g. position axis after we remove a some-sort of  linear profile. This is the function of detrending that I have applied. Thee reason to do it is to first detect any vibrations or non-standard fluctuations and directy get the frequency composition of it. In principle, one should be able to see the natural frequency if we directly subject the axes data to FFT without any detrending. However, physically this will also depend on the  resonance around 12 Hz which would be the case in case of vibrations.

**Comment by Kelks19** [comment]
I have also included a small note to check when was the compensation mode last enabled.

**Review by ltoribiosc — APPROVED** [review]
The changes have been implemented and the branch can be merged

**Pull request merged**
