### PR TITLE
Tickets/sitcom 411

### PR DESCRIPTION
**Pull request by bstalder**
New notebook for ComCam.  Need some help with getting data from the EFD.

### CODE REVIEW

**Comment by b1quint** [comment]
We can either query the EFD or query the events from the CSC themselves. If you want, I can try to come up with something. If I understand correctly, you want more precision in the time between sending a command to start changing the filter (`command_setFilter`?) and the moment it arrives at its position (`logevent_endLoadFilter` or `logevent_endSetFilter`?). Is that correct?

**Comment by bstalder** [comment]
> 

Yes Bruno, setFilter to endSetFilter sounds right.  We also want to record the position (linear encoder) after each movement to a particular filter slot.

**Comment by isotuela** [comment]
Hi Bruno, Holger, 
The requested changes have been implemented. If you could please review it, I´d be grateful. Many thanks for your time!

Ioana

**Review by hdrass — APPROVED** [review]
Thanks, Ioana! Looks very good to me! Looking forward to the results from ComCam.

**Comment by b1quint** [comment]
Looks great! 
@isotuela, can you use a standard logger call instead of `DecoratedLog` since it hasn't been working in the new versions of Nublado? And could you rebase your branch to ensure that the `efd.py` module is in this branch, please?

**Review by b1quint — CHANGES_REQUESTED** [review]
Please, see my comments above.

**Comment by b1quint** [comment]
We discussed the test case during the V&V meeting, and we also need some statistics regarding the filter's position from the linear encoder. Can we have a median/mean/std of the difference between the actual position and the commanded position? Ideally, we want these stats from 0->1, 1->2, 2->1, 1->0.  

We would also want some statistics on the time it took to change positions.

Finally, since we are trying to use this test case to characterize the filter changer, we would like to repeat the movements much more, so we have statistically relevant data. Maybe we should change the loop to run 50 times (meaning that we would go to each position at least ten times)?

The test case is now updated, and I believe it is more precise. Could you have a look and see if you can implement it accordingly?

**Review by b1quint — APPROVED** [review]
We probably want to split this notebook in two (data acquisition and data analysis) like the others, but this is good for now.

**Pull request merged**
