### PR TITLE
Tickets/sitcom 1282

### PR DESCRIPTION
**Pull request by nsevilla**
This is a script to programatically create a BLOCK with pairs of stars for star tracker tests.

### CODE REVIEW

**Comment by ltoribiosc** [comment]
This script selects star pairs for tracking testing taking in account the separation between stars, elevation and magnitud.

I have some doubts about the `compute_pair_list` function, especially in the `for i,(refstar,refhd)` loop... 

What is `refhd` used for and what is its function? In the first part of the loop, until the `if`, it is not used for anything, but it confuses me that it is the first statement in the loop. I have the same comment for `hd2`

**Comment by ltoribiosc** [comment]
In the same loop (`for i,(refstar,refhd) in enumerate(stars_altaz_hd):`), it calculates the value of `az` in two different ways, in addition to an `alt_old` that is not used at all. I'm not sure if this second `az` could be a bug or a part of the code that was not deleted

**Comment by nsevilla** [comment]
> In the same loop (`for i,(refstar,refhd) in enumerate(stars_altaz_hd):`), it calculates the value of `az` in two different ways, in addition to an `alt_old` that is not used at all. I'm not sure if this second `az` could be a bug or a part of the code that was not deleted

Fixed

**Comment by nsevilla** [comment]
> This script selects star pairs for tracking testing taking in account the separation between stars, elevation and magnitud.
> 
> I have some doubts about the `compute_pair_list` function, especially in the `for i,(refstar,refhd)` loop...
> 
> What is `refhd` used for and what is its function? In the first part of the loop, until the `if`, it is not used for anything, but it confuses me that it is the first statement in the loop. I have the same comment for `hd2`

It is the HD denomination of the star (Henry Draper Catalog), needed to write the BLOCK. I download that information previously at 

hd = table[selection_vmag]['HD']

and zip it with the rest of the star information

**Review by ltoribiosc — APPROVED** [review]

**Pull request merged**
