### PR TITLE
Update SITCOM-989 M1M3 ICS Analysis Notebook to use new module

### PR DESCRIPTION
**Pull request by b1quint**

### CODE REVIEW

**Review by psferguson — APPROVED** [review]
This looks good, I included a few minor comments

**Comment by b1quint** [comment]
<p>I added a link to the tech note where all the details will be. This is simpler because, then, I have all the detailed documentation in a single place.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/notebooks_vandv/pull/74/discussion/#comment-1806152135'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by b1quint** [comment]
<p>I made the log less verbose. However, not sure I can add tqdm without breaking summit_utils. I need to talk to Merlin before that. </p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/notebooks_vandv/pull/74/discussion/#comment-1806152188'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by b1quint** [comment]
<p>I removed this part. The analysis associated with a whole obsday is in another notebook being produced by PR#84.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/notebooks_vandv/pull/74/discussion/#comment-1806161429'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
