### PR TITLE
Tickets/sitcom 516

### PR DESCRIPTION
**Pull request by b1quint**

### CODE REVIEW

**Review by hdrass — APPROVED** [review]
Not critical: fixed-dome-startracker.ipynb has execution details in the notebook.

Looks fine to me! Thanks to all contributors.

**Comment by cwwalter** [comment]
As I  mentioned there are few things that need to be changed (you can see the fixed-dome notebook for reference).

Here are the ones I see:

- The SAL indexes are different on the summit than at the TTS

It should be

```
camera_sal_indexes = [101, 102]
```

- In the `for index in camera_sal_indexes:` cell

The `break` will break the loop and only get you one camera
You don't need the ComCam here. I think you were using it at TTS to get a 2nd camera.

@tribeiro Do you see anything else we changed?

**Review by cwwalter — CHANGES_REQUESTED** [review]
See comments in the comment box.

**Comment by cwwalter** [comment]
OK looks good to me now.

**Review by cwwalter — APPROVED** [review]

**Pull request merged**
