### PR TITLE
Tickets/sitcom 1486

### PR DESCRIPTION
**Pull request by Kelks19**
TEA Vibration analysis using M2Hexapod telemetries.

### CODE REVIEW

**Comment by ltoribiosc** [comment]
This notebook is a continuation of the analysis performed in SITCOM-1485. 

Please update in the description text at the beginning of the notebook, after “Analysis details” is indicated “This analysis focusses on **MTCam hexapods**...” when it should be “This analysis focusses on **MTM2Hexapod**...”.

**Comment by ltoribiosc** [comment]
If you can change some minor typos: 
- In the cell after define def calculate_fft_app is written “becuase” instead of “because”.
- Initaite the EFD -> Initiate the EFD

**Comment by ltoribiosc** [comment]
I don't understand the discussion part after the position plots. Why do you say “, it may still indicate an external influence or inherent signal that may affect the Cam Hexapod”? Are you comparing results from the sitcom-1485 or is it a mistake and it should say “M2Hexapod”?

**Comment by ltoribiosc** [comment]
Also in the discussion part you state “During a 2 minute window in the TEA vibration, we detect a characteristic peak frequency of ~7.2 Hz” but in the plots it is ~7.3 Hz. This is slightly different than when CamHexapod was analyzed. In this case for all positions the peak frequency is ~7.3 Hz.

**Comment by ltoribiosc** [comment]
The latest conclusions also seem to be not updated and talk about CamHexapod.

**Comment by ltoribiosc** [comment]
The rest of the notebook is well understood and follows the same structure as SITCOM-1485.

**Comment by Kelks19** [comment]
1. Done
2. Done
3. It should say M2Hexapod 
4. So a difference of 0.1 Hz is not going be resolvable with Hexapods. Unless we specifically verify with an an extended sample which are not. Hence it is safe to assume a frequency of ~7 Hz 
5. Updated

**Review by ltoribiosc — APPROVED** [review]
The notebook has been corrected and some clarifications have been added to the discussion.

**Pull request merged**
