### PR TITLE
SITCOM-710: Analysis to find max velocity, acceleration, and jerk values for all identified slews

### PR DESCRIPTION
**Pull request by psferguson**
This branch is tied to https://github.com/lsst-sitcom/sitcomtn-068/blob/u/pferguso/v1/index.rst (still a rough draft)

### CODE REVIEW

**Review by bstalder — DISMISSED** [review]
please put the parquet table creation calls in the notebook, so can run everything in one go (with proper py imports).

**Comment by craiglagegit** [comment]
Hi Miranda.  I ran the notebook and I have several comments:
(1) On the last two plots, I would start the plot a second or two before the start of the slew, and continue it a second or two after the end.  Then you can see when the slew starts and ends.  This can be done with the padding parameters in tmaUtils.py

(2) On all of the plots, you have chosen a time when the velocities were very small, less than 1 deg/sec.  Why not choose a time with more realistic velocities?  On the last plot, you can't even see the velocities, accelerations, and jerks, because the mount is moving so slowly.

**Comment by mirarenee** [comment]
Hi Craig,
Thanks for the feedback. I've added 2 seconds of padding and choose a better example slew that has faster movement.

**Review by craiglagegit — APPROVED** [review]
This looks much better!  Thanks for the changes.  I'm approving it.  Go ahead and merge.  Don't forget to delete the branch after you merge.

**Pull request merged**
