### PR TITLE
Added function to unpack accelerometer data.

### PR DESCRIPTION
**Pull request by jfcrenshaw**

### CODE REVIEW

**Comment by b1quint** [comment]
Can you update the `__init__.py` file to allow import the `accelerometer.py` file together with the other files?

**Comment by b1quint** [comment]
I did the following experiment to confirm the timestamps: 
```
for i in range(100):
    try:
        assert df.index[i] == t[i*200]
    except AssertionError:
        print(f"Assert failed for {i} - df.index[i] = {df.index[i]} and t[i*200] = {t[i*200]}")
```
A few of these failed but due to numerical error. We are good in terms of timestamps. The only change I will ask is the one in the previous comment above.

**Comment by jfcrenshaw** [comment]
@b1quint done!

by the way, a good way to perform the timestamp comparison without hitting precision errors is this:
```python
assert np.isclose(df.index[i].timestamp(), t[200*i].timestamp())
```

**Review by b1quint — APPROVED** [review]
That's great! Thank you very much! You can go ahead and merge!

**Pull request merged**
